//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WORD_GAME.rc
//
#define ID_STOP                         3
#define ID_REGISTER                     3
#define IDCANCEL2                       3
#define ID_START                        4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WORD_GAME_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_USER                        130
#define IDD_USER_LOG                    130
#define IDD_MUSIC                       131
#define IDR_WAVE1                       137
#define IDR_WAVE2                       138
#define IDR_WAVE3                       139
#define IDR_WAVE4                       140
#define IDR_WAVE5                       141
#define IDD_USER_REGISTER               148
#define IDD_IMAGE                       149
#define IDD_RANK                        155
#define IDD_HARD                        156
#define IDD_RULE                        157
#define IDB_BITMAP1                     173
#define IDB_BITMAP2                     174
#define IDB_BITMAP3                     175
#define IDB_BITMAP4                     176
#define IDB_BITMAP5                     177
#define IDB_BITMAP6                     178
#define IDB_BITMAP7                     179
#define IDB_BITMAP8                     180
#define IDI_ICON1                       182
#define IDB_BITMAP9                     183
#define IDB_BITMAP10                    186
#define IDB_BITMAP11                    187
#define IDB_BITMAP12                    188
#define IDB_BITMAP13                    189
#define IDB_BITMAP14                    190
#define IDB_BITMAP15                    191
#define IDB_BITMAP16                    192
#define IDB_BITMAP17                    193
#define IDB_BITMAP18                    194
#define IDB_BITMAP_SCORE                196
#define IDB_BITMAP19                    198
#define IDB_BITMAP20                    199
#define IDB_BITMAP21                    200
#define IDB_BITMAP22                    201
#define IDB_BITMAP23                    202
#define IDB_BITMAP24                    203
#define IDB_BITMAP25                    204
#define IDB_BITMAP26                    205
#define IDB_BITMAP27                    206
#define IDB_BITMAP28                    207
#define IDB_BITMAP29                    208
#define IDB_BITMAP30                    209
#define IDB_BITMAP31                    210
#define IDB_BITMAP32                    212
#define IDB_BITMAP33                    213
#define IDB_BITMAP34                    214
#define IDC_BUTTONQ                     1000
#define IDC_BUTTONW                     1001
#define IDC_BUTTONE                     1002
#define IDC_BUTTONR                     1003
#define IDC_BUTTONT                     1004
#define IDC_BUTTONY                     1005
#define IDC_BUTTONU                     1006
#define IDC_BUTTONI                     1007
#define IDC_BUTTONO                     1008
#define IDC_BUTTONP                     1009
#define IDC_BUTTONA                     1010
#define IDC_BUTTONS                     1011
#define IDC_BUTTOND                     1012
#define IDC_BUTTONF                     1013
#define IDC_BUTTONG                     1014
#define IDC_BUTTONH                     1015
#define IDC_BUTTONJ                     1016
#define IDC_BUTTONCAPSLOCK              1017
#define IDC_BUTTONK                     1018
#define IDC_BUTTONL                     1019
#define IDC_BUTTONZ                     1020
#define IDC_BUTTONX                     1021
#define IDC_BUTTONC                     1022
#define IDC_BUTTONV                     1023
#define IDC_BUTTONB                     1024
#define IDC_BUTTONN                     1025
#define IDC_BUTTONM                     1026
#define IDC_NAME                        1027
#define IDC_BUTTONEnter                 1028
#define IDC_NAMEA                       1030
#define IDC_BUTTONBACKSPACE             1031
#define IDC_NAME1                       1032
#define IDC_NAMEB                       1033
#define IDC_SCORE                       1034
#define IDC_NAME2                       1035
#define IDC_RADIO1                      1036
#define IDC_RADIO2                      1037
#define IDC_COUNT                       1038
#define IDC_WRITE_HARD                  1039
#define IDC_OUT                         1040
#define IDC_MOVE                        1041
#define IDC_MUSIC                       1042
#define IDC_EDIT_USERNAME               1043
#define IDC_EDIT_NICK                   1044
#define IDC_TIME                        1045
#define IDC_EDIT_NICKNAME               1045
#define IDC_EDIT_CODE                   1045
#define IDC_PROCESS                     1045
#define IDC_NOW                         1046
#define IDC_LIST1                       1049
#define IDC_LIST                        1050
#define IDC_MAKE                        1051
#define IDC_STATIC_MUSIC                1051
#define IDC_RADIO_NULL                  1056
#define IDC_RADIO_BALL                  1057
#define IDC_RADIO_SNOW                  1058
#define IDC_RADIO_FISH                  1059
#define IDC_STATIC_IMAGE                1060
#define IDC_COMBO1                      1066
#define IDC_COMBO2                      1067
#define IDC_STATIC_NAME1                1067
#define IDC_COMBO3                      1068
#define IDC_STATIC_NAME2                1068
#define IDC_COMBO4                      1069
#define IDC_STATIC_NAME3                1069
#define IDC_STATIC_NAME4                1070
#define IDC_STATIC_NAME5                1071
#define IDC_STATIC_SCORE1               1072
#define IDC_STATIC_SCORE2               1073
#define IDC_STATIC_SCORE3               1074
#define IDC_STATIC_SCORE4               1075
#define IDC_STATIC_SCORE5               1076
#define IDC_shezhihao                   1077
#define IDC_BNU                         1078
#define IDC_STATIC_GAME                 1079
#define IDC_STATIC_IMAGE_TYPE           1080
#define IDC_STATIC_BACK_MUSIC           1081
#define IDC_STATIC_MOVE                 1082
#define IDC_STATIC_HZ                   1083
#define IDC_STATIC_HARD                 1084
#define IDC_STATIC_COUNT                1085
#define IDC_STATIC_YONGHU               1086
#define IDC_STATIC_XUANXIANG            1087
#define IDC_STATIC_JIANPAN              1088
#define IDC_STATIC_XIAN1                1089
#define IDC_STATIC_XIAN2                1090
#define IDC_STATIC_XIAN3                1091
#define IDC_STATIC_XIAN4                1092
#define IDC_STATIC_XIAN5                1093
#define IDC_STATIC_XIAN6                1094
#define IDC_STATIC_XIAN7                1095
#define ID_RULE                         32773
#define ID_ABOUT                        32774
#define ID_USER                         32775
#define ID_HARD                         32776
#define ID_IMAGE                        32777
#define ID_MUSIC                        32778
#define ID_RANK                         32779
#define ID_LOG                          32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
